run:
  build-tags:
    - gles
    - darwin
    - js
  timeout: 5m
  allow-parallel-runners: true
  go: '1.24'
  # Skip problematic directories
  skip-dirs:
    - github.com/go-gl/gl/v3.1/gles2
    - fyne.io/fyne/v2/internal/painter/gl

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-dirs:
    - github.com/go-gl/gl
    - github.com/go-gl/glfw
    - fyne.io/fyne/v2/internal/painter/gl
  exclude-dirs-use-default: true
  exclude-files:
    - ".*_test\\.go$"
  exclude-rules:
    - path: fyne.io/fyne
      linters:
        - all
    - path: github.com/go-gl
      linters:
        - all
    # Exclude GLES2 package issues
    - path: github.com/go-gl/gl/v3.1/gles2
      linters:
        - all 