version: 2

project_name: trtc-go

before:
  hooks:
    - go mod tidy

builds:
  - id: trtc-go-cli
    main: ./cmd/cli
    binary: trtc-go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

  # Build GUI only for macOS natively with CGO enabled
  - id: trtc-go-gui-darwin
    main: ./cmd/gui
    binary: trtc-go-gui
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
      
  # Build GUI for Windows and Linux with GLES tag
  - id: trtc-go-gui-windows-linux
    main: ./cmd/gui
    binary: trtc-go-gui
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=gles
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: trtc-go-archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: chatt-state
    name: trtc-go
  prerelease: auto
  draft: false
  name_template: "{{ .ProjectName }} v{{ .Version }}"

