version: 2

project_name: trtc-go

before:
  hooks:
    - go mod tidy

# Add timeout to the release section
release:
  github:
    owner: chatt-state
    name: trtc-go
  prerelease: auto
  draft: false
  name_template: "{{ .ProjectName }} v{{ .Version }}"

builds:
  # GUI builds with CGO enabled
  - id: trtc-go-gui
    main: ./cmd/gui
    binary: trtc-go-gui
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/chatt-state/trtc-go/cmd/gui.Version={{.Version}}
    flags:
      - -trimpath

# Use faster compression
archives:
  - id: trtc-go-gui-archives
    name_template: "trtc-go-gui_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
    format: zip
    format_overrides:
      - goos: linux
        format: tar.xz
        
# Skip unnecessary steps for faster builds
checksum:
  name_template: "trtc-go_{{ .Version }}_checksums.txt"
  algorithm: sha256

# Optimize changelog generation
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch 