version: 2

project_name: trtc-go

before:
  hooks:
    - go mod tidy
    # Install fyne-cross for proper cross-compilation in GitHub Actions
    - go install github.com/fyne-io/fyne-cross@latest
    # Make sure Docker is running and pull the fyne-cross image
    - docker pull fyneio/fyne-cross:latest
    # Create a directory for cross-compiled binaries
    - mkdir -p dist/fyne-cross
    # Build for Windows using fyne-cross with GLES tag
    - fyne-cross windows -arch=amd64,arm64 -output trtc-go-gui -app-id com.chattstate.trtc-go -app-version {{.Version}} -ldflags="-s -w -X main.Version={{.Version}}" -tags=gles ./cmd/gui
    # Build for Linux using fyne-cross with GLES tag
    - fyne-cross linux -arch=amd64,arm64 -output trtc-go-gui -app-id com.chattstate.trtc-go -app-version {{.Version}} -ldflags="-s -w -X main.Version={{.Version}}" -tags=gles ./cmd/gui
    # Copy the cross-compiled binaries to the dist directory for goreleaser to include in the release
    - cp -r fyne-cross/bin/* dist/

builds:
  - id: trtc-go-cli
    main: ./cmd/cli
    binary: trtc-go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

  # Build GUI only for macOS natively with CGO enabled
  - id: trtc-go-gui-darwin
    main: ./cmd/gui
    binary: trtc-go-gui
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
      
  # Build GUI for Windows and Linux with GLES tag
  - id: trtc-go-gui-windows-linux
    main: ./cmd/gui
    binary: trtc-go-gui
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=gles
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: trtc-go-archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - dist/fyne-cross/**/*  # Include the cross-compiled binaries
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: chatt-state
    name: trtc-go
  prerelease: auto
  draft: false
  name_template: "{{ .ProjectName }} v{{ .Version }}"

