project_name: trtc-go

before:
  hooks:
    - go mod tidy

builds:
  - id: trtc-go-cli
    main: ./cmd/cli
    binary: trtc-go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: trtc-go-gui
    main: ./cmd/gui
    binary: trtc-go-gui
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: trtc-go-archives
    builds:
      - trtc-go-cli
      - trtc-go-gui
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - icon.png

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: chscc
    name: trtc-go
  prerelease: auto
  draft: false
  name_template: "{{ .ProjectName }} v{{ .Version }}" 