version: 2

project_name: trtc-go

before:
  hooks:
    - go mod tidy

# Add timeout to the release section
release:
  github:
    owner: chatt-state
    name: trtc-go
  prerelease: auto
  draft: false
  name_template: "{{ .ProjectName }} v{{ .Version }}"
  footer: |
    ## Installation
    
    Download the appropriate package for your operating system and architecture.
    
    For more information, see the [README.md](https://github.com/chatt-state/trtc-go/blob/main/README.md).

builds:
  # CLI builds only (no GUI, no OpenGL dependencies)
  - id: trtc-go-cli
    main: ./cmd/cli
    binary: trtc-go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/chatt-state/trtc-go/cmd/cli.Version={{.Version}}
    flags:
      - -trimpath

# Use faster compression
archives:
  - id: trtc-go-cli-archives
    name_template: "trtc-go-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
    format: zip
    format_overrides:
      - goos: linux
        format: tar.gz
        
# Skip unnecessary steps for faster builds
checksum:
  name_template: "trtc-go_{{ .Version }}_checksums.txt"
  algorithm: sha256

# Optimize changelog generation
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  use_github_release_notes: false
  abbrev: 0
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Other Changes'
      order: 999 