repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.54.2
    hooks:
      - id: golangci-lint

  - repo: local
    hooks:
      - id: go-test
        name: go test
        description: Run go tests
        entry: bash -c 'go test -v ./...'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-build
        name: go build
        description: Check if the code builds
        entry: bash -c 'go build -v ./cmd/cli && go build -v ./cmd/gui'
        language: system
        types: [go]
        pass_filenames: false 