repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.2
    hooks:
      - id: golangci-lint
        args: [--timeout=3m]

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-mod-tidy
      - id: validate-toml

  - repo: local
    hooks:
      - id: go-build
        name: go build
        description: Check if the code builds
        entry: bash -c 'go build ./...'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-test
        name: go test
        description: Run go tests
        entry: bash -c 'go test ./...'
        language: system
        types: [go]
        pass_filenames: false 