name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: go.sum
      
      # Install dependencies first to avoid export data issues
      - name: Install Dependencies
        run: go mod download -x
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          # Explicitly use our config file and add build tags
          args: --timeout=3m --config=.golangci.yml --build-tags=gles,darwin,js
          skip-cache: true
          # Only run on changed files for PRs
          only-new-issues: true 