name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: go.sum
      
      # Install dependencies first to avoid export data issues
      - name: Install Dependencies
        run: go mod download -x
      
      # First lint only CLI code (more reliable)
      - name: Lint CLI Code
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m --config=.golangci.yml --out-format=colored-line-number ./cmd/cli/... ./pkg/... ./internal/config/... ./internal/api/...
          skip-cache: true
          only-new-issues: true
      
      # Try to lint GUI code separately (may be skipped if it fails)
      - name: Lint GUI Code
        continue-on-error: true
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m --config=.golangci.yml --out-format=colored-line-number --build-tags=gles,darwin,js ./cmd/gui/... ./internal/ui/...
          skip-cache: true
          only-new-issues: true 