name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      # Install dependencies for GUI builds
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev gcc pkg-config

      # Install fyne-cross for proper cross-compilation
      - name: Install fyne-cross
        run: |
          go install github.com/fyne-io/fyne-cross@latest
          echo "fyne-cross version:"
          fyne-cross version

      # Extract version from tag
      - name: Set Version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"

      # Build CLI with GoReleaser (no CGO needed)
      - name: Build CLI with GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --timeout 30m --config .goreleaser.cli.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build GUI for each platform using fyne-cross
      # fyne-cross automatically sets the appropriate environment for each platform
      - name: Build GUI for Windows
        run: |
          fyne-cross windows -arch=amd64 -output trtc-go-gui -app-id "io.github.chatt-state.trtc-go" -app-version ${{ env.VERSION }} -ldflags="-X=github.com/chatt-state/trtc-go/cmd/gui.Version=${{ env.VERSION }}" ./cmd/gui

      - name: Build GUI for macOS
        run: |
          fyne-cross darwin -arch=amd64 -output trtc-go-gui -app-id "io.github.chatt-state.trtc-go" -app-version ${{ env.VERSION }} -ldflags="-X=github.com/chatt-state/trtc-go/cmd/gui.Version=${{ env.VERSION }}" ./cmd/gui

      - name: Build GUI for Linux
        run: |
          fyne-cross linux -arch=amd64 -output trtc-go-gui -app-id "io.github.chatt-state.trtc-go" -app-version ${{ env.VERSION }} -ldflags="-X=github.com/chatt-state/trtc-go/cmd/gui.Version=${{ env.VERSION }}" ./cmd/gui

      # Upload GUI builds to the release
      - name: Upload GUI Builds to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            fyne-cross/dist/windows-amd64/trtc-go-gui.exe
            fyne-cross/dist/darwin-amd64/trtc-go-gui.app.zip
            fyne-cross/dist/linux-amd64/trtc-go-gui.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 